### ISSUE TITLE
Questions this benchmark should answer

### ISSUE THREAD

**Issue by basejump** [9ci/grails-gorm-benchmarks#5]
keep drilling down so we can answer the needed questions
- fastest way to persist/insert gorm
- does binding slow it down (yes), why (started exaplantion), best alternative ….
- does valiation slow it down (yes), why ….
- does auditstamp slow it down (yest), how to fix now that we know
- does dao slow it down ……
- does idGenerator slow it down or speed it up
- does compile static speed things up
 I added these to readme

**Comment by snimavat** [comment]
I have completely refactored all benchmarks https://github.com/9ci/grails-gorm-benchmarks/commit/a62b249449a254572c992b4a46b10d4ee355f4ff (edited)


[10:04] 
- Added script to run all benchmarks automatically
- Added benchmark for idgenerator
- Without dao


[10:05] 
Updated all sections of README other then figures. I wont update figures with my numbers any more as they are almost same all the type with just one or two seconds  difference. So i wont be updating it every time i run it on my machine. I will update the numbers as we run it on a standard test box


[10:06] 
I did not put answers right below ur bullet points. But the readme explains it all.
It gives conclusion about what is fastest, What is worst, effect of databinding, validation, audit trail and reason for it.


[10:08] 
If you have further changes in mind for readme. It would help if you update read me and point me exactly which parts u would like to be updated.


[10:10] 
run-bechmarks.sh will run all the benchmarks and will output results on console. It will run with and without audittrail, with autowire enabled/disabled and without/without idgenerator
